import './menu/menu'
// import './menu/dockMenu'
import './settings/settings'
import './util/electronOperations'
import './videoDownload/videoDownload'
import './videoDownload/videoType/m3u8Video/m3u8Video'
import './videoDownload/finishList/finishList'
import './videoDownload/analysis/analysisLink/analysisDownloadLink'
import './videoDownload/analysis/search/searchResource'
import './videoDownload/videoType/magnet/magnet'
import './videoDownload/videoPlay/videoPlay'
